//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PerfectlyMadeInc.WebEx.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IntegrationState
    {
        public long IntegrationStateId { get; set; }
        public long EventId { get; set; }
        public AutomationSystem.Base.Contract.Enums.EntityTypeEnum EntityTypeId { get; set; }
        public long EntityId { get; set; }
        public Nullable<long> AttendeeId { get; set; }
        public AutomationSystem.Base.Contract.Enums.IntegrationStateTypeEnum IntegrationStateTypeId { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
        public string ErrorMessage { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Street { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string ZipCode { get; set; }
        public string Email { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual IntegrationStateType IntegrationStateType { get; set; }
        public virtual Event Event { get; set; }
    }
}
