//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLocalisation
    {
        public long AppLocalisationId { get; set; }
        public AutomationSystem.Base.Contract.Enums.LanguageEnum LanguageId { get; set; }
        public string Module { get; set; }
        public string Label { get; set; }
        public string Value { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
