//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchUpload
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchUpload()
        {
            this.BatchUploadItems = new HashSet<BatchUploadItem>();
        }
    
        public long BatchUploadId { get; set; }
        public AutomationSystem.Base.Contract.Enums.BatchUploadTypeEnum BatchUploadTypeId { get; set; }
        public AutomationSystem.Base.Contract.Enums.BatchUploadStateEnum BatchUploadStateId { get; set; }
        public string Name { get; set; }
        public Nullable<long> FileId { get; set; }
        public AutomationSystem.Base.Contract.Enums.EntityTypeEnum UploadedEntityTypeId { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.EntityTypeEnum> ParentEntityTypeId { get; set; }
        public Nullable<long> ParentEntityId { get; set; }
        public System.DateTime Uploaded { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public string JsonParameters { get; set; }
    
        public virtual BatchUploadState BatchUploadState { get; set; }
        public virtual BatchUploadType BatchUploadType { get; set; }
        public virtual File File { get; set; }
        public virtual EntityType ParentEntityType { get; set; }
        public virtual EntityType UploadedEntityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchUploadItem> BatchUploadItems { get; set; }
    }
}
