//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchUploadItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BatchUploadItem()
        {
            this.BatchUploadFields = new HashSet<BatchUploadField>();
        }
    
        public long BatchUploadItemId { get; set; }
        public long BatchUploadId { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.BatchUploadOperationTypeEnum> BatchUploadOperationTypeId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public Nullable<long> PairEntityId { get; set; }
        public bool IsValid { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<System.DateTime> Processed { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchUploadField> BatchUploadFields { get; set; }
        public virtual BatchUploadOperationType BatchUploadOperationType { get; set; }
        public virtual BatchUpload BatchUpload { get; set; }
    }
}
