//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailTemplate()
        {
            this.EmailTemplateParameters = new HashSet<EmailTemplateParameter>();
            this.Emails = new HashSet<Email>();
        }
    
        public long EmailTemplateId { get; set; }
        public AutomationSystem.Base.Contract.Enums.LanguageEnum LanguageId { get; set; }
        public AutomationSystem.Base.Contract.Enums.EmailTypeEnum EmailTypeId { get; set; }
        public bool IsDefault { get; set; }
        public bool IsLocalisable { get; set; }
        public bool IsSealed { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.EntityTypeEnum> EntityTypeId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public string FillingNote { get; set; }
        public bool IsValidated { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public bool IsHtml { get; set; }
    
        public virtual EmailType EmailType { get; set; }
        public virtual EntityType EntityType { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailTemplateParameter> EmailTemplateParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Email> Emails { get; set; }
    }
}
