//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class File
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public File()
        {
            this.EmailAttachments = new HashSet<EmailAttachment>();
            this.BatchUploads = new HashSet<BatchUpload>();
        }
    
        public long FileId { get; set; }
        public string Name { get; set; }
        public string FileName { get; set; }
        public AutomationSystem.Base.Contract.Enums.FileTypeEnum FileTypeId { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.LanguageEnum> LanguageId { get; set; }
        public byte[] Data { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public bool IsPublic { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailAttachment> EmailAttachments { get; set; }
        public virtual FileType FileType { get; set; }
        public virtual Language Language { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchUpload> BatchUploads { get; set; }
    }
}
