//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Incident()
        {
            this.IncidentChildren = new HashSet<Incident>();
        }
    
        public long IncidentId { get; set; }
        public Nullable<long> ParentIncidentId { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.EntityTypeEnum> EntityTypeId { get; set; }
        public Nullable<long> EntityId { get; set; }
        public AutomationSystem.Base.Contract.Enums.IncidentTypeEnum IncidentTypeId { get; set; }
        public string Message { get; set; }
        public string Description { get; set; }
        public System.DateTime Occurred { get; set; }
        public bool CanBeReport { get; set; }
        public bool IsReported { get; set; }
        public int ReportingAttempts { get; set; }
        public Nullable<System.DateTime> Reported { get; set; }
        public bool IsResolved { get; set; }
        public Nullable<System.DateTime> Resolved { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public string IpAddress { get; set; }
        public string RequestUrl { get; set; }
        public string HandlerCode { get; set; }
        public bool IsHidden { get; set; }
    
        public virtual EntityType EntityType { get; set; }
        public virtual IncidentType IncidentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incident> IncidentChildren { get; set; }
        public virtual Incident IncidentParent { get; set; }
    }
}
