//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.JobRuns = new HashSet<JobRun>();
        }
    
        public long JobId { get; set; }
        public string Name { get; set; }
        public AutomationSystem.Base.Contract.Enums.JobTypeEnum JobTypeId { get; set; }
        public string JsonParameter { get; set; }
        public int IntervalInMinutes { get; set; }
        public int FromHour { get; set; }
        public int FromMinute { get; set; }
        public int Severity { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual JobType JobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobRun> JobRuns { get; set; }
    }
}
