//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobRun
    {
        public long JobRunId { get; set; }
        public long JobId { get; set; }
        public string JsonResult { get; set; }
        public AutomationSystem.Base.Contract.Enums.ProcessingStateEnum ProcessingStateId { get; set; }
        public int Severity { get; set; }
        public bool Active { get; set; }
        public System.DateTime Planned { get; set; }
        public Nullable<System.DateTime> Started { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual ProcessingState ProcessingState { get; set; }
    }
}
