//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalRecord
    {
        public long PayPalRecordId { get; set; }
        public string PayPalId { get; set; }
        public decimal Amount { get; set; }
        public decimal Fee { get; set; }
        public string CountryCode { get; set; }
        public string Email { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PayerId { get; set; }
        public string SaRecipientName { get; set; }
        public string SaLine1 { get; set; }
        public string SaLine2 { get; set; }
        public string SaCity { get; set; }
        public string SaState { get; set; }
        public string SaPostalCode { get; set; }
        public string SaCountryCode { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public string FeeText { get; set; }
        public string TransactionId { get; set; }
    }
}
