//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Shared.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayPalKey
    {
        public long PayPalKeyId { get; set; }
        public string Name { get; set; }
        public string BraintreeToken { get; set; }
        public string Environment { get; set; }
        public bool Active { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.UserGroupTypeEnum> UserGroupTypeId { get; set; }
        public Nullable<long> UserGroupId { get; set; }
        public AutomationSystem.Base.Contract.Enums.CurrencyEnum CurrencyId { get; set; }
    
        public virtual User User { get; set; }
        public virtual UserGroupType UserGroupType { get; set; }
    }
}
