//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRegistration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassRegistration()
        {
            this.ClassRegistrationFiles = new HashSet<ClassRegistrationFile>();
            this.ClassRegistrationInvitations = new HashSet<ClassRegistrationInvitation>();
        }
    
        public long ClassRegistrationId { get; set; }
        public long StudentAddressId { get; set; }
        public string StudentEmail { get; set; }
        public Nullable<long> RegistrantAddressId { get; set; }
        public string RegistrantEmail { get; set; }
        public AutomationSystem.Base.Contract.Enums.LanguageEnum LanguageId { get; set; }
        public long ClassId { get; set; }
        public AutomationSystem.Base.Contract.Enums.RegistrationTypeEnum RegistrationTypeId { get; set; }
        public AutomationSystem.Base.Contract.Enums.RegistrationFormTypeEnum RegistrationFormTypeId { get; set; }
        public long ClassRegistrationPaymentId { get; set; }
        public Nullable<long> FormerStudentId { get; set; }
        public bool AreAgreementsAccepted { get; set; }
        public bool IsTemporary { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public AutomationSystem.Base.Contract.Enums.ApprovementTypeEnum ApprovementTypeId { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public Nullable<long> ClassRegistrationLastClassId { get; set; }
        public string StudentPhone { get; set; }
        public string RegistrantPhone { get; set; }
        public long ProfileId { get; set; }
        public bool IsReviewed { get; set; }
    
        public virtual Address RegistrantAddress { get; set; }
        public virtual Address StudentAddress { get; set; }
        public virtual ApprovementType ApprovementType { get; set; }
        public virtual ClassRegistrationLastClass ClassRegistrationLastClass { get; set; }
        public virtual ClassRegistrationPayment ClassRegistrationPayment { get; set; }
        public virtual FormerStudent FormerStudent { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual RegistrationFormType RegistrationFormType { get; set; }
        public virtual RegistrationType RegistrationType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRegistrationFile> ClassRegistrationFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRegistrationInvitation> ClassRegistrationInvitations { get; set; }
        public virtual Class Class { get; set; }
    }
}
