//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class()
        {
            this.ClassActions = new HashSet<ClassAction>();
            this.ClassBusinesses = new HashSet<ClassBusiness>();
            this.ClassFiles = new HashSet<ClassFile>();
            this.ClassMaterials = new HashSet<ClassMaterial>();
            this.ClassPersons = new HashSet<ClassPerson>();
            this.ClassRegistrations = new HashSet<ClassRegistration>();
            this.ClassRegistrationInvitations = new HashSet<ClassRegistrationInvitation>();
            this.DistanceClassTemplateClasses = new HashSet<DistanceClassTemplateClass>();
        }
    
        public long ClassId { get; set; }
        public AutomationSystem.Base.Contract.Enums.ClassTypeEnum ClassTypeId { get; set; }
        public string Location { get; set; }
        public System.DateTime EventStartUtc { get; set; }
        public System.DateTime EventStart { get; set; }
        public System.DateTime EventEndUtc { get; set; }
        public System.DateTime EventEnd { get; set; }
        public AutomationSystem.Base.Contract.Enums.TimeZoneEnum TimeZoneId { get; set; }
        public long CoordinatorId { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.LanguageEnum> TransLanguageId { get; set; }
        public bool IsWwaFormAllowed { get; set; }
        public long PriceListId { get; set; }
        public Nullable<long> PayPalKeyId { get; set; }
        public Nullable<System.DateTime> RegistrationStartUtc { get; set; }
        public Nullable<System.DateTime> RegistrationStart { get; set; }
        public System.DateTime RegistrationEndUtc { get; set; }
        public System.DateTime RegistrationEnd { get; set; }
        public bool IsCanceled { get; set; }
        public Nullable<System.DateTime> Canceled { get; set; }
        public bool IsFinished { get; set; }
        public Nullable<System.DateTime> Finished { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public AutomationSystem.Base.Contract.Enums.EnvironmentTypeEnum EnvironmentTypeId { get; set; }
        public AutomationSystem.Base.Contract.Enums.IntegrationTypeEnum IntegrationTypeId { get; set; }
        public Nullable<long> IntegrationEntityId { get; set; }
        public Nullable<long> GuestInstructorId { get; set; }
        public long ClassBusinessId { get; set; }
        public long ClassReportSettingId { get; set; }
        public long ClassStyleId { get; set; }
        public long ProfileId { get; set; }
        public AutomationSystem.Base.Contract.Enums.LanguageEnum OriginLanguageId { get; set; }
        public AutomationSystem.Base.Contract.Enums.CurrencyEnum CurrencyId { get; set; }
        public AutomationSystem.Base.Contract.Enums.ClassCategoryEnum ClassCategoryId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual TimeZone TimeZone { get; set; }
        public virtual ClassBusiness ClassBusiness { get; set; }
        public virtual ClassCategory ClassCategory { get; set; }
        public virtual ClassReportSetting ClassReportSetting { get; set; }
        public virtual ClassStyle ClassStyle { get; set; }
        public virtual ClassType ClassType { get; set; }
        public virtual Person Coordinator { get; set; }
        public virtual Person GuestInstructor { get; set; }
        public virtual PriceList PriceList { get; set; }
        public virtual Profile Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassAction> ClassActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassBusiness> ClassBusinesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassFile> ClassFiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassMaterial> ClassMaterials { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassPerson> ClassPersons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRegistration> ClassRegistrations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRegistrationInvitation> ClassRegistrationInvitations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistanceClassTemplateClass> DistanceClassTemplateClasses { get; set; }
    }
}
