//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassMaterialDownloadLog
    {
        public long ClassMaterialDownloadLogId { get; set; }
        public long ClassMaterialFileId { get; set; }
        public System.DateTime Time { get; set; }
        public string IpAddress { get; set; }
        public bool WasDownloaded { get; set; }
        public string Message { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public long ClassMaterialRecipientId { get; set; }
    
        public virtual ClassMaterialFile ClassMaterialFile { get; set; }
        public virtual ClassMaterialRecipient ClassMaterialRecipient { get; set; }
    }
}
