//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRegistrationFile
    {
        public long ClassRegistrationFileId { get; set; }
        public long ClassRegistrationId { get; set; }
        public long FileId { get; set; }
        public string DisplayedName { get; set; }
        public System.DateTime Assigned { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public string Code { get; set; }
    
        public virtual ClassRegistration ClassRegistration { get; set; }
    }
}
