//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassRegistrationPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClassRegistrationPayment()
        {
            this.ClassRegistrations = new HashSet<ClassRegistration>();
        }
    
        public long ClassRegistrationPaymentId { get; set; }
        public string CheckNumber { get; set; }
        public string TransactionNumber { get; set; }
        public Nullable<decimal> PayPalFee { get; set; }
        public Nullable<decimal> TotalPayPal { get; set; }
        public Nullable<decimal> TotalCheck { get; set; }
        public Nullable<decimal> TotalCash { get; set; }
        public Nullable<decimal> TotalCreditCard { get; set; }
        public Nullable<long> PayPalRecordId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public bool IsPaidPmi { get; set; }
        public bool IsAbsentee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClassRegistration> ClassRegistrations { get; set; }
    }
}
