//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactListItem
    {
        public long ContactListItemId { get; set; }
        public long ContactListId { get; set; }
        public string Email { get; set; }
        public long FormerStudentId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual FormerStudent FormerStudent { get; set; }
        public virtual ContactList ContactList { get; set; }
    }
}
