//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceClassTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DistanceClassTemplate()
        {
            this.DistanceClassTemplateClasses = new HashSet<DistanceClassTemplateClass>();
            this.DistanceClassTemplatePersons = new HashSet<DistanceClassTemplatePerson>();
        }
    
        public long DistanceClassTemplateId { get; set; }
        public AutomationSystem.Base.Contract.Enums.ClassTypeEnum ClassTypeId { get; set; }
        public string Location { get; set; }
        public System.DateTime EventStart { get; set; }
        public System.DateTime EventEnd { get; set; }
        public Nullable<AutomationSystem.Base.Contract.Enums.LanguageEnum> TransLanguageId { get; set; }
        public AutomationSystem.Base.Contract.Enums.LanguageEnum OriginLanguageId { get; set; }
        public System.DateTime RegistrationStart { get; set; }
        public System.DateTime RegistrationEnd { get; set; }
        public Nullable<long> GuestInstructorId { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<System.DateTime> Completed { get; set; }
        public Nullable<System.DateTime> AutomationCompleteTime { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual ClassType ClassType { get; set; }
        public virtual Person GuestInstructor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistanceClassTemplateClass> DistanceClassTemplateClasses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistanceClassTemplatePerson> DistanceClassTemplatePersons { get; set; }
    }
}
