//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistanceClassTemplateClass
    {
        public long DistanceClassTemplateClassId { get; set; }
        public long DistanceClassTemplateId { get; set; }
        public long ClassId { get; set; }
        public long DistanceProfileId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual DistanceProfile DistanceProfile { get; set; }
        public virtual DistanceClassTemplate DistanceClassTemplate { get; set; }
        public virtual Class Class { get; set; }
    }
}
