//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MainEntities : DbContext
    {
        public MainEntities()
            : base("name=MainEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<TimeZone> TimeZones { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<ApprovementType> ApprovementTypes { get; set; }
        public virtual DbSet<ClassPerson> ClassPersons { get; set; }
        public virtual DbSet<ClassRegistrationInvitation> ClassRegistrationInvitations { get; set; }
        public virtual DbSet<ClassType> ClassTypes { get; set; }
        public virtual DbSet<PersonRole> PersonRoles { get; set; }
        public virtual DbSet<PersonRoleType> PersonRoleTypes { get; set; }
        public virtual DbSet<RegistrationFormType> RegistrationFormTypes { get; set; }
        public virtual DbSet<RegistrationType> RegistrationTypes { get; set; }
        public virtual DbSet<PriceListItem> PriceListItems { get; set; }
        public virtual DbSet<FormerStudent> FormerStudents { get; set; }
        public virtual DbSet<ClassRegistrationLastClass> ClassRegistrationLastClasses { get; set; }
        public virtual DbSet<PriceListType> PriceListTypes { get; set; }
        public virtual DbSet<ClassFile> ClassFiles { get; set; }
        public virtual DbSet<ClassRegistrationFile> ClassRegistrationFiles { get; set; }
        public virtual DbSet<ClassRegistrationPayment> ClassRegistrationPayments { get; set; }
        public virtual DbSet<ClassBusiness> ClassBusinesses { get; set; }
        public virtual DbSet<ClassExpense> ClassExpenses { get; set; }
        public virtual DbSet<ClassExpenseType> ClassExpenseTypes { get; set; }
        public virtual DbSet<ClassPreferenceExpense> ClassPreferenceExpenses { get; set; }
        public virtual DbSet<ClassStyle> ClassStyles { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<ProfileUser> ProfileUsers { get; set; }
        public virtual DbSet<RegistrationColorScheme> RegistrationColorSchemes { get; set; }
        public virtual DbSet<ClassMaterialFile> ClassMaterialFiles { get; set; }
        public virtual DbSet<ClassAction> ClassActions { get; set; }
        public virtual DbSet<ClassActionType> ClassActionTypes { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<RoyaltyFeeRate> RoyaltyFeeRates { get; set; }
        public virtual DbSet<RoyaltyFeeRateType> RoyaltyFeeRateTypes { get; set; }
        public virtual DbSet<PriceList> PriceLists { get; set; }
        public virtual DbSet<ClassPreference> ClassPreferences { get; set; }
        public virtual DbSet<ClassReportSetting> ClassReportSettings { get; set; }
        public virtual DbSet<ClassMaterial> ClassMaterials { get; set; }
        public virtual DbSet<ClassMaterialRecipient> ClassMaterialRecipients { get; set; }
        public virtual DbSet<ClassRegistration> ClassRegistrations { get; set; }
        public virtual DbSet<ClassMaterialDownloadLog> ClassMaterialDownloadLogs { get; set; }
        public virtual DbSet<DistanceClassTemplateClass> DistanceClassTemplateClasses { get; set; }
        public virtual DbSet<DistanceClassTemplatePerson> DistanceClassTemplatePersons { get; set; }
        public virtual DbSet<DistanceProfile> DistanceProfiles { get; set; }
        public virtual DbSet<DistanceClassTemplate> DistanceClassTemplates { get; set; }
        public virtual DbSet<ContactBlackList> ContactBlackLists { get; set; }
        public virtual DbSet<ContactListItem> ContactListItems { get; set; }
        public virtual DbSet<FormerClass> FormerClasses { get; set; }
        public virtual DbSet<ContactList> ContactLists { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<ClassCategory> ClassCategories { get; set; }
    
        public virtual int ClearClassCertificates(Nullable<System.DateTime> toDate, ObjectParameter rowcount)
        {
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearClassCertificates", toDateParameter, rowcount);
        }
    
        public virtual int ClearClassMaterialFiles(Nullable<System.DateTime> toDate, ObjectParameter rowcount)
        {
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearClassMaterialFiles", toDateParameter, rowcount);
        }
    
        public virtual int ClearClassRegistrationCertificates(Nullable<System.DateTime> toDate, ObjectParameter rowcount)
        {
            var toDateParameter = toDate.HasValue ?
                new ObjectParameter("ToDate", toDate) :
                new ObjectParameter("ToDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ClearClassRegistrationCertificates", toDateParameter, rowcount);
        }
    }
}
