//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceList()
        {
            this.PriceListItems = new HashSet<PriceListItem>();
            this.DistanceProfiles = new HashSet<DistanceProfile>();
            this.Classes = new HashSet<Class>();
        }
    
        public long PriceListId { get; set; }
        public string Name { get; set; }
        public bool IsApprovded { get; set; }
        public Nullable<System.DateTime> Approved { get; set; }
        public bool IsDiscarded { get; set; }
        public Nullable<System.DateTime> Discarded { get; set; }
        public int OwnerId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
        public AutomationSystem.Base.Contract.Enums.PriceListTypeEnum PriceListTypeId { get; set; }
        public AutomationSystem.Base.Contract.Enums.CurrencyEnum CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual PriceListType PriceListType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceListItem> PriceListItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DistanceProfile> DistanceProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
    }
}
