//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomationSystem.Main.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceListItem
    {
        public long PriceListItemId { get; set; }
        public long PriceListId { get; set; }
        public AutomationSystem.Base.Contract.Enums.RegistrationTypeEnum RegistrationTypeId { get; set; }
        public decimal Price { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Changed { get; set; }
        public bool Deleted { get; set; }
    
        public virtual RegistrationType RegistrationType { get; set; }
        public virtual PriceList PriceList { get; set; }
    }
}
